dist: xenial
language: csharp
dotnet: 2.2
mono: none
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
    - ASPNETCORE_ENVIRONMENT="Production"
    - PATH="$PATH:/home/travis/.dotnet/tools"
script:
 - dotnet restore
 - dotnet build 
